### ISSUE TITLE
Does rvv-opcodes include all instructions in rvv-1.0?

### ISSUE THREAD

**Issue by naveen126** [riscv/riscv-opcodes#103]
Hi Sir,
I have some problems.
(1) I can not find some instructions in rvv-opcodes, such as vlseg3e32 and vluxseq3ei32.v, ...
(2) vslideup.vi has a unsigned imm5, but it has simm5 in rvv-opcodes.

Please give confirmation for these problems.

Thanks!

**Comment by aswaterman** [comment]
(1) The `nf` field distinguishes segment loads/stores from regular loads/stores.  For example, vlseg3e32.v is the `nf`=2 case of this instruction: https://github.com/riscv/riscv-opcodes/blob/2497a8cc120a9d30d0cc9bf01372dc2efbefbc25/opcodes-rvv#L25

(2) rvv-opcodes is only concerned with the bit positions of the operands, not their meanings.  So there is no distinction between simm5 and uimm5.
