### ISSUE TITLE
Spurious character in install target

### ISSUE THREAD

**Issue by kwalker27** [riscv/riscv-opcodes#109]
https://github.com/riscv/riscv-opcodes/blob/47bc49ace128d8d9272be6098870d6f919ccbaa4/Makefile#L46

As far as I can tell, this 'c' doesn't serve any purpose, and actually breaks `make install`.

```
make: *** No rule to make target 'c', needed by 'install'.  Stop.
```

**Comment by aswaterman** [comment]
Yeah, apparently the CI flow doesn't test `make install`.  (Of course, `make install` may well break for other reasons, like not having the `riscv-pk` and `riscv-tests` repos checked out in `..`.)

**Comment by aswaterman** [comment]
e13a2ec9433a6900feafd260fa9bb3374ab531c7
