### ISSUE TITLE
HINTs are no longer emitted in encoding.out.h

### ISSUE THREAD

**Issue by aswaterman** [riscv/riscv-opcodes#125]
...which breaks Spike.  (If you copy the file into the HEAD of riscv-isa-sim master, you'll see what I mean.)

@neelgala can you resolve this one?

cf. https://github.com/riscv-software-src/riscv-isa-sim/issues/1020

**Comment by aswaterman** [comment]
@neelgala can you resolve this one?

**Comment by aswaterman** [comment]
related issue: https://github.com/riscv-software-src/riscv-isa-sim/issues/1020

**Comment by neelgala** [comment]
I will look into this asap.

**Comment by aswaterman** [comment]
Thank you!

**Comment by aswaterman** [comment]
Resolved by https://github.com/riscv/riscv-opcodes/pull/126
