### ISSUE TITLE
Latex Control Sequence \instbit and \instbitrange not included

### ISSUE THREAD

**Issue by stephengeerlings** [riscv/riscv-opcodes#14]
I am missing these control sequences in the generated tex files. Am I missing a library? Or were these functions forgotten to be included?

**Comment by aswaterman** [comment]
The generated latex files don't stand alone.  They are meant to be used in the context of https://github.com/riscv/riscv-isa-manual

**Comment by stephengeerlings** [comment]
Thanks for the quick reply! Sorry for opening an issue!

**Comment by aswaterman** [comment]
That's what issues are for :)

**Comment by pbreuer** [comment]
Can someone point to the .sty filein the archive where those macros are defined (better, note it in the table .tex file)? The table allegedly generated by pandoc from the priv-instr-table.tex file at  https://five-embeddev.com/riscv-isa-manual/latest/priv-insns.html#priv-instr-table seems to be absent without leave, and I would like to (re)create the missing table.

Regards

PTB

**Comment by Fighter19** [comment]
@pbreuer 
The old commands were defined in this file:
https://github.com/riscv/riscv-isa-manual/blob/pause-public-review-20201013/src/preamble.tex
