### ISSUE TITLE
Cannot turn tex files into PDF

### ISSUE THREAD

**Issue by gareth-anthony-hulse** [riscv/riscv-opcodes#171]
When attempting to turn `instr-table.tex` and `priv-instr-table.tex` into PDFs, it just spits out a ton of errors.  You can get the logs here: [latex-error-logs.zip](https://github.com/riscv/riscv-opcodes/files/11128505/latex-error-logs.zip) produced from [TeX Studio](https://archlinux.org/packages/community/x86_64/texstudio/).

**Specs:** https://linux-hardware.org/?probe=1146b0ebfc

**Comment by neelgala** [comment]
those tex files are meant to replade the respective files in riscv-isa-manual repo and not meant to be used as standalone.

**Comment by gareth-anthony-hulse** [comment]
I was hoping to get all the RISC-V instructions in a nice layout with binary representation, such as in the RISC-V spec from the chapter titled 'RV32/64G Instruction Set Listings'.
