### ISSUE TITLE
Unclear grammar / Exceptions to instruction syntax

### ISSUE THREAD

**Issue by tomhepworth** [riscv/riscv-opcodes#204]
I am having a go at writing a parser and I notice that most instructions are described by the format in the README  

IE `<instruction name> <instruction args> <bit-encodings>`

However there seem to be exceptions to this eg in `rv64_i`:

```
sraiw   rd rs1 31..25=32 shamtw 14..12=5 6..2=0x06 1..0=3
```

where bit encodings appear to be mixed with instruction arguments.

Is this a mistake or am I missing something?

Parsers could be written a lot easier with a consistent format.

**Comment by aswaterman** [comment]
The format is consistent; it's just that args and bit encodings may be intermixed.  The only requirement is that the name is the first token and the others come later.

**Comment by tomhepworth** [comment]
Perhaps the README should be updated to reflect this, since (at least to me) it currently implies that they are distinct. 

Perhaps just something like `<instruction name> <instruction args / bit encodings>`

**Comment by tomhepworth** [comment]
Or better: `<instruction name> <arguments>` with a note that `<argument> := <bit encoding> | <variable argument>`

**Comment by aswaterman** [comment]
I agree, and your most recent version is nicely concise while being accurate.  If you PR it, I'll merge it.

**Comment by tomhepworth** [comment]
On it :)

**Comment by sequencer** [comment]
FWIW, I wrote a Scala decoder here: https://github.com/sequencer/rvdecoderdb

**Comment by tomhepworth** [comment]
Nice, I am making one in Haskell
