### ISSUE TITLE
Bug report (#define INSN_FIELD_RS2=RS1 0x1f00000)

### ISSUE THREAD

**Issue by YenHaoChen** [riscv/riscv-opcodes#287]
There is a bug in generated encoding.h. Spike gets warnings when compilation.

![image](https://github.com/user-attachments/assets/1b0a3aef-155d-4909-a790-14e9d9f4a504)

The line was introduced by https://github.com/riscv/riscv-opcodes/pull/279.

**Comment by aswaterman** [comment]
Yeah, this issue was raised in #284.  The author is aware of the bug and will submit a PR soon.
