### ISSUE TITLE
Old names 

### ISSUE THREAD

**Issue by AFOliveira** [riscv/riscv-opcodes#301]
Are things like `#Old names for fmv.x.w/fmv.w.x` truly needed in the repo? Shouldn't someone working on older versions use an older version of the repo?
The problem is that this gets parsed as a pseudo-instruction, which can mislead people trying to look for information.

**Comment by aswaterman** [comment]
But as the spec says, "To avoid disturbing existing code, both the W and S versions will be supported by tools."

That's a roundabout way of saying that they _are_ pseudoinstructions.

**Comment by AFOliveira** [comment]
Oh ok, that was a really helpful clarification. Thanks!
