### ISSUE TITLE
Vector encodings

### ISSUE THREAD

**Issue by AFOliveira** [riscv/riscv-opcodes#322]
Hello, I was checking this repo info against binutils and came across this:

Isn't nf supposed to be constant in this type of instructions?

https://github.com/riscv/riscv-opcodes/blob/4d8d26037e0b5198175193d6fee3cbc830ebb688/extensions/rv_v#L23

**Comment by aswaterman** [comment]
It's a way of specifying all of the segment loads without listing them out as individual instructions.  In other words, this definition of vle8.v includes the definition of vlsegNe8.v, too.

In general, the distinction between having multiple instructions and having a single instruction with an additional argument is pretty fuzzy.  The story with AMOs and the aq/rl bits is similar.

I don't think we need to take any action.

**Comment by AFOliveira** [comment]
As in that case, I was also not super sure about this, so thank you so much for the clarification.
