### ISSUE TITLE
HFENCE.BVMA incorrect?

### ISSUE THREAD

**Issue by baltazarortiz** [riscv/riscv-opcodes#43]
`opcodes-system` has an encoding for "`hfence.vvma`" but not `hfence.bvma`. I'm guessing this is a typo, but figured I'd check before setting up a one-character PR.

**Comment by aswaterman** [comment]
Reasonable guess, but actually the instruction was renamed: https://github.com/riscv/riscv-isa-manual/blob/a2ae53f289802e8857516404ab8d2591d614aedb/src/hypervisor.tex#L1740

**Comment by baltazarortiz** [comment]
Good to know, thanks! I was looking at the version of the manual on the website (V20190608-Priv-MSU-Ratified) rather than github, so it hasn't been updated yet.
