### ISSUE TITLE
Why shamt in this repo is [25:20]

### ISSUE THREAD

**Issue by Phantom1003** [riscv/riscv-opcodes#47]
https://github.com/riscv/riscv-opcodes/blob/8d59eaae6d42e5dffa71846eb8296a8a5a461994/parse_opcodes#L36

Hi, I found that the opcodes in above line is [25:20], which should be [24:20] in spec. Is there is a miswrite, or I miss something ?

**Comment by 2henwei** [comment]
It means bit24-20 in Python

**Comment by Phantom1003** [comment]
> It means bit24-20 in Python

No, I do not think so, rd is defined:
```python
arglut['rd'] = (11,7)
```
[11:7] follows description in spec
![image](https://user-images.githubusercontent.com/39120057/90650422-71198800-e26e-11ea-83e2-f91f4b2f50c2.png)

**Comment by kito-cheng** [comment]
RV64 uses the bit 25 as the 6-th bit for shamt.

[image: image.png]

**Comment by kito-cheng** [comment]
![image](https://user-images.githubusercontent.com/2723185/90662734-500b6400-e27b-11ea-9312-6534f0676c10.png)

**Comment by Phantom1003** [comment]
Got it, thanks, but I found that 32i also use the 6-bit shamt, may be there is a bug ?

**Comment by aswaterman** [comment]
There's an alias for the RV32I version of SLLI: https://github.com/riscv/riscv-opcodes/blob/8d59eaae6d42e5dffa71846eb8296a8a5a461994/opcodes-pseudo#L2

Note that one uses `shamtw`, which uses bits 24:20.
