### ISSUE TITLE
Platform-specific details in encoding.h

### ISSUE THREAD

**Issue by dpetrisko** [riscv/riscv-opcodes#58]
https://github.com/riscv/riscv-opcodes/blob/d2ef643520da334443a9c99fd107a9487ad7c4b9/encoding.h#L209

```
#define DEFAULT_RSTVEC     0x00001000
#define CLINT_BASE         0x02000000
#define CLINT_SIZE         0x000c0000
#define EXT_IO_BASE        0x40000000
#define DRAM_BASE          0x80000000
```

Correct me if I'm wrong, but these are platform specific details and seem like they don't belong in a "canonical" RISC-V definitions file

**Comment by aswaterman** [comment]
This stuff is here for legacy reasons and probably should be removed.
