### ISSUE TITLE
Missing Vector Integer Add-with-Carry / Subtract-with-Borrow Instructions Opcodes

### ISSUE THREAD

**Issue by drom** [riscv/riscv-opcodes#69]
The following instructions mentioned in spec:

## 11.4. Vector Integer Add-with-Carry / Subtract-with-Borrow Instructions

But missing in `opcodes-rvv` file

```
vmadc.vv
vmadc.vx
vmadc.vi

vmsbc.vv
vmsbc.vx
```

**Comment by 2henwei** [comment]
They use the same encoding space with vm*bc.v*m with a bit `vm`. Don't think they have to be added explicitly.
