### ISSUE TITLE
Provide a standard format output (json?)

### ISSUE THREAD

**Issue by josharian** [riscv/riscv-opcodes#7]
It'd be useful for new consumers of riscv-opcodes for parse-opcodes to have a standardized output format, such as json, in addition to language-specific generators. That'll keep the core simple; people can write their own generators from json to their language of choice out of the tree.

For bonus points, commit the generated json for the core RISC-V ISA when anything changes. Then folks can just grab the json instead of having to get the repo up and running (see #6).

I should also say: Thanks so much for having this. So much nicer than transcribing opcodes from a PDF. :)

**Comment by aswaterman** [comment]
OK, I'm gonna close this for now.  We'd certainly review a PR that spits out json or yaml or the like; it's just not a priority for us to create it ourselves at the moment.  As you surmised, the overgrown python script just serves as a pragmatic means to generate our source code and documentation, and wasn't meant to be very general.
