### ISSUE TITLE
Missing 15. Vector Mask Instructions

### ISSUE THREAD

**Issue by drom** [riscv/riscv-opcodes#72]
The following instructions mentioned in spec:

## 15. Vector Mask Instructions

But missing in `opcodes-rvv` file

```
vmmv.m
vmclr.m
vmset.m
vmnot.m

vcpop.m
```

**Comment by 2henwei** [comment]
Those are pseudo-instructions. I don't think they should be handled here.

**Comment by drom** [comment]
Agree, for
```
vmmv.m
vmclr.m
vmset.m
vmnot.m
```

Should they go to: `opcodes-rvv-pseudo` ?

**Comment by drom** [comment]
As for `vcpop.m` it looks like rename:

`vpopc.m --> vcpop.m`

**Comment by 2henwei** [comment]
Ah I see. I didn't know there was pseudo functionality in the parser. Yeh, they could go to pseudo-files.

**Comment by 2henwei** [comment]
I just took a look through the parser. Seems that pseudo-instruction is not kinda same meaning as one in the assembler. It looks more like aliasing for instructions. I guess this is for legacy purpose like instructions being renamed and old names are retained.
